# -*- coding: utf-8 -*-
"""Jianyi(Nancy)Teng_final_project_fake_news_detect(model_optimization).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o92BembKq-_UkVUjzW_TdcoXyd1QjsFY

##a. LIBRARY INSTALL AND IMPORT
"""

pip cache purge

!pip install pandas numpy scikit-learn torch transformers tqdm checklist

!pip install ipywidgets

# This cell will authenticate you and mount your Drive in the Colab.
from google.colab import drive
drive.mount('/content/drive')

#Import all necessary libraries
import re
import nltk
import os
import json
import pandas as pd
import torch
import numpy as np
from sklearn.utils import resample
from transformers import BertTokenizer, BertModel
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

# check some numpy version
print(f"NumPy version: {np.__version__}")

"""#b.DATA

###b1.DATA LOADING
"""

import json
import pandas as pd

# Function to read a JSON file
def load_json_file(file_path):
    """Load a JSON file"""
    with open(file_path, "r", encoding="utf-8") as file:
        return json.load(file)

# Function to process FakeNewsNet data
def process_FakeNewsNet_data(file_paths):
    """Read multiple JSON files and organize them into a DataFrame"""
    data_list = []  # Store all data

    for category, file_path in file_paths.items():
        data = load_json_file(file_path)  # Load JSON data

        for news_id, news_content in data.items():
            if 'text' in news_content:  # Ensure the text field exists
                # Determine the news source
                if "gossipcop" in category:
                    source = "gossipcop"
                elif "politifact" in category:
                    source = "politifact"
                else:
                    source = "unknown"

                # Determine the news type
                if "R" in category:
                    if "HR" in category:
                        label = "human_real" # Human-written real news
                    else:
                        label = "gpt_real"  # AI-generated real news
                elif "F" in category:
                    if "MF" in category:
                        label = "gpt_fake"  # AI-generated fake news
                    else:
                        label = "human_fake"  # Human-written fake news
                else:
                    label = "unknown"

                data_list.append({
                    "id": news_id,
                    "text": news_content["text"],
                    "title": news_content.get("title", ""),  # Some data may not have a title
                    "source": source,  # News source
                    "label": label,  # Real/fake news category
                })

    # Convert to a Pandas DataFrame
    df = pd.DataFrame(data_list)
    return df

# Define paths for the dataset
fake_news_paths = {
    "gossipcop_HF": "/content/drive/MyDrive/DS266/HF.json",
    "gossipcop_HR": "/content/drive/MyDrive/DS266/HR.json",
    "gossipcop_MF": "/content/drive/MyDrive/DS266/MF.json",
    "gossipcop_MR": "/content/drive/MyDrive/DS266/MR.json",
}

# Load and process the data
FakeNewsNet_df = process_FakeNewsNet_data(fake_news_paths)

# Display the first 5 rows
FakeNewsNet_df.head()

"""# c.Model Optmization
Direction
1. gpt fake & gpt real have shorter text, balance the length
  1.  reduce current length
  2.  data augmentation
2. humanize gpt text by adding typo for gpt real & fake
3. two stage model


"""

!pip install -q transformers
!pip install -q torchinfo
!pip install -q datasets
!pip install -q evaluate

import numpy as np

import transformers
import evaluate

from datasets import load_dataset
from torchinfo import summary

from transformers import AutoTokenizer, AutoModel, AutoModelForSequenceClassification
from transformers import TrainingArguments, Trainer

import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

import nltk
nltk.download('stopwords')
nltk.download('punkt')

from datasets import Dataset
import pandas as pd

from sklearn.metrics import confusion_matrix, classification_report
import numpy as np


from transformers import Trainer, TrainingArguments
import torch
import numpy as np
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

"""#### C1: gpt fake & gpt real have shorter text, balance the length"""

# combine text and title for training
FakeNewsNet_df['combined_text'] = FakeNewsNet_df['text'] + '.' + FakeNewsNet_df['title']

FakeNewsNet_df["word_count"] = FakeNewsNet_df["combined_text"].apply(lambda x: len(x.split()))


MR =  FakeNewsNet_df[(FakeNewsNet_df['label'] == "gpt_real") & (FakeNewsNet_df['word_count'] < 500) & (FakeNewsNet_df['word_count'] > 80)]
MF =  FakeNewsNet_df[(FakeNewsNet_df['label'] == "gpt_fake") & (FakeNewsNet_df['word_count'] < 500) & (FakeNewsNet_df['word_count'] > 80)]
HR =  FakeNewsNet_df[(FakeNewsNet_df['label'] == "human_real") & (FakeNewsNet_df['word_count'] < 500) & (FakeNewsNet_df['word_count'] > 80)]
HF =  FakeNewsNet_df[(FakeNewsNet_df['label'] == "human_fake") & (FakeNewsNet_df['word_count'] < 500) & (FakeNewsNet_df['word_count'] > 80)]


new_FNN_df = pd.concat([MR,MF,HR,HF])

print(new_FNN_df['label'].value_counts())

##lowest is 2756

MR = resample(MR,replace=True,n_samples=2756,random_state=42)
MF = resample(MF,replace=True,n_samples=2756,random_state=42)
HR = resample(HR,replace=True,n_samples=2756,random_state=42)


Bal_FNN_df = pd.concat([MR,MF,HR,HF])

print(Bal_FNN_df['label'].value_counts())

# Convert labels to numerical values (0=real, 1=fake)
Bal_FNN_df['label_new'] = Bal_FNN_df['label'].map({'human_fake': 0, 'human_real': 1.0,'gpt_fake': 2,'gpt_real':3})

# calcalate word count distributon of news text
Bal_FNN_df["word_count"] = Bal_FNN_df["combined_text"].apply(lambda x: len(x.split()))
Bal_FNN_df.groupby("label")["word_count"].describe()

import string

def simple_tokenizer(text):
    return re.findall(r'\b\w+\b', text.lower())

text = "Hello! This is a test."
print(simple_tokenizer(text))

# Remove unwanted characters, links, and HTML tags
def clean_text(text):
    # Remove HTML tags
    text = re.sub(r'<.*?>', '', text)
    # Remove URLs
    text = re.sub(r'http\S+|www\S+|https\S+', '', text)
    # Remove special characters and numbers, keeping only letters
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()
    # Convert to lowercase
    text = text.lower()
    words = simple_tokenizer(text)
    stop_words = set(stopwords.words('english'))
    filtered_words = [word for word in words if word not in stop_words]
    return ' '.join(filtered_words)

# Apply cleaning to datasets
Bal_FNN_df['cleaned_combined_text'] = Bal_FNN_df['combined_text'].apply(clean_text)

from sklearn.model_selection import train_test_split

# Split the data while keeping the DataFrame structure ( for hugging face dataset use)

train_df, tmp_df = train_test_split(
    Bal_FNN_df[['cleaned_combined_text', 'label_new']],
    test_size=0.4,
    random_state=42,
    stratify=Bal_FNN_df['label_new']
)

val_df, test_df = train_test_split(
    tmp_df,
    test_size=0.5,
    random_state=42,
    stratify=tmp_df['label_new']
)
# Reset the index for both DataFrames
train_df = train_df.reset_index(drop=True)
test_df = test_df.reset_index(drop=True)
val_df = val_df.reset_index(drop=True)

print(f"Training samples: {len(train_df)}")
print(f"Test samples: {len(test_df)}")
print(f"Val samples: {len(test_df)}")
print("\nTrain DataFrame:")
print(train_df.head())
print("\nTest DataFrame:")
print(test_df.head())
print("\nVal DataFrame:")
print(val_df.head())

from checklist.perturb import Perturb

def safe_add_typos(text, min_length=3, max_typos=2):
    if pd.isna(text) or len(text) < min_length:
        return text

    try:
        n_typos = min(max_typos, len(text)//2)  # Max 1 typo per 2 characters
        return Perturb.add_typos(text)
    except ValueError:
        return text  # Fallback for edge cases

def conditional_add_typos(row):
        return safe_add_typos(row['cleaned_combined_text'])




train_df['text_add_typos'] = train_df.apply(conditional_add_typos, axis=1)

# test_df['text_add_typos'] = test_df.apply(conditional_add_typos, axis=1)

# val_df['text_add_typos'] = val_df.apply(conditional_add_typos, axis=1)


# train_df['text_add_typos'] = train_df['cleaned_combined_text'].apply(safe_add_typos)

# # Verify
# empty_count = train_df['cleaned_combined_text'].apply(lambda x: len(x) < 3).sum()
# print(f"Fixed {empty_count} short/empty texts")

train_df.drop(columns=['cleaned_combined_text'], inplace=True)
# test_df.drop(columns=['cleaned_combined_text'], inplace=True)
# val_df.drop(columns=['cleaned_combined_text'], inplace=True)

# Convert to Hugging Face Dataset for training
formatted_df = train_df.rename(columns={
    'text_add_typos': 'text',
    'label_new': 'label'
})

fake_news_dataset_train = Dataset.from_pandas(formatted_df)

# Convert to Hugging Face Dataset for testimg
formatted_df = test_df.rename(columns={
    'cleaned_combined_text': 'text',
    'label_new': 'label'
})

fake_news_dataset_test = Dataset.from_pandas(formatted_df)

# Convert to Hugging Face Dataset for validating
formatted_df = val_df.rename(columns={
    'cleaned_combined_text': 'text',
    'label_new': 'label'
})

fake_news_dataset_val = Dataset.from_pandas(formatted_df)

print("Test: \n",fake_news_dataset_test)
print("Train: \n",fake_news_dataset_train)
print("Val: \n",fake_news_dataset_val)

MAX_SEQUENCE_LENGTH = 496

# Encode data

def preprocess_data(data, tokenizer):
    review_text = data['text']

    encoded = tokenizer.batch_encode_plus(
            review_text,
            max_length=MAX_SEQUENCE_LENGTH,
            padding='max_length',
            truncation=True,
            return_attention_mask=True,
            return_token_type_ids=True,
            return_tensors="pt"
        )

    return encoded

#Creating  compute metrics function

metric = evaluate.load('accuracy')

# FakeNewsNet_df['label_new'] = FakeNewsNet_df['label'].map({'human_fake': 0, 'human_real': 1.0,'gpt_fake': 2,'gpt_real': 3})
def compute_metrics(eval_pred):
  predictions, labels = eval_pred
  predictions = np.argmax(predictions, axis=1)
  precision, recall, f1, _ = precision_recall_fscore_support(labels, predictions, average='weighted')
  acc = accuracy_score(labels, predictions)

  class_report = classification_report(
        labels, predictions,
        target_names=['human_fake', 'human_real', 'gpt_fake','gpt_real'],
        digits=4
    )
  print("\nClassification Report:")
  print(class_report)

  return {
      'accuracy': acc,
      'f1': f1,
      'precision': precision,
      'recall': recall
  }

## Fine tuning the "bert-base-cased" model

def fine_tune_classification_model(classification_model,
                                   tokenizer,
                                   train_data,
                                   val_data,
                                   batch_size = 16,
                                   num_epochs = 3):

    preprocessed_train_data = train_data.map(preprocess_data, batched=True, fn_kwargs={'tokenizer': tokenizer})
    preprocessed_val_data = val_data.map(preprocess_data, batched=True, fn_kwargs={'tokenizer': tokenizer})

    preprocessed_train_data = preprocessed_train_data.map(
        lambda x: {'labels': torch.tensor(x['label'], dtype=torch.long)}  # Ensure labels are int64
    )
    preprocessed_val_data  = preprocessed_val_data .map(
        lambda x: {'labels': torch.tensor(x['label'], dtype=torch.long)}
    )



    training_args = TrainingArguments(
    output_dir="/content/drive/MyDrive/DS266/model_output",
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size,
    num_train_epochs=num_epochs,
    logging_dir="/content/drive/MyDrive/DS266/logs",
    eval_strategy="epoch",
    save_strategy="epoch",
    report_to='none'
)
    trainer = Trainer(
        model=classification_model,
        args=training_args,
        train_dataset=preprocessed_train_data,
        eval_dataset=preprocessed_val_data,
        compute_metrics=compute_metrics
    )


    trainer.train()



"""### bert-base model"""

model_checkpoint_name = "bert-base-cased"
bert_tokenizer = AutoTokenizer.from_pretrained(model_checkpoint_name)
# bert_classification_model = AutoModelForSequenceClassification.from_pretrained(model_checkpoint_name)

bert_classification_model = AutoModelForSequenceClassification.from_pretrained(
    model_checkpoint_name,
    num_labels=4  # number of classes = 4
)

# fine_tune_classification_model(bert_classification_model, bert_tokenizer, fake_news_dataset_train, fake_news_dataset_val)

fine_tune_classification_model(bert_classification_model, bert_tokenizer, fake_news_dataset_train, fake_news_dataset_val)

"""### roberta-base model"""

model_checkpoint_name = "roberta-base"
roberta_tokenizer = AutoTokenizer.from_pretrained(model_checkpoint_name)
roberta_classification_model = AutoModelForSequenceClassification.from_pretrained(
    model_checkpoint_name,
    num_labels=4  # number of classes = 4
)

fine_tune_classification_model(roberta_classification_model, roberta_tokenizer, fake_news_dataset_train, fake_news_dataset_val)

"""### c2.Data Augment"""

# remove extrame long text
# combine text and title for training
FakeNewsNet_df['combined_text'] = FakeNewsNet_df['text'] + '.' + FakeNewsNet_df['title']

FakeNewsNet_df["word_count"] = FakeNewsNet_df["combined_text"].apply(lambda x: len(x.split()))


MR =  FakeNewsNet_df[(FakeNewsNet_df['label'] == "gpt_real") & (FakeNewsNet_df['word_count'] < 1000)]
MF =  FakeNewsNet_df[(FakeNewsNet_df['label'] == "gpt_fake") & (FakeNewsNet_df['word_count'] < 1000) ]
HR =  FakeNewsNet_df[(FakeNewsNet_df['label'] == "human_real") & (FakeNewsNet_df['word_count'] < 1000) ]
HF =  FakeNewsNet_df[(FakeNewsNet_df['label'] == "human_fake") & (FakeNewsNet_df['word_count'] < 1000) ]


new_FNN_df = pd.concat([MR,MF,HR,HF])

print(new_FNN_df['label'].value_counts())

##lowest is 2756

new_FNN_df["word_count"] = new_FNN_df["combined_text"].apply(lambda x: len(x.split()))
new_FNN_df.groupby("label")["word_count"].describe()

# For here, we would like to match gpt fake with human fake
# and match gpt real with human real.

target_stats = {
    'human_fake': {'mean': 338, 'std': 204, 'min': 5, 'max': 993},
    'human_real': {'mean': 358, 'std': 220, 'min': 4, 'max': 998}
}

target_length_gpt_fake = int(np.clip(
    np.random.normal(loc=target_stats['human_fake']['mean'],
                    scale=target_stats['human_fake']['std']),
    target_stats['human_fake']['min'],
    target_stats['human_fake']['max']
))

print(target_length_gpt_fake)


target_length_gpt_real = int(np.clip(
    np.random.normal(loc=target_stats['human_real']['mean'],
                    scale=target_stats['human_real']['std']),
    target_stats['human_real']['min'],
    target_stats['human_real']['max']
))

print(target_length_gpt_real)

from transformers import pipeline
import numpy as np

# Initialize text generation pipeline
generator = pipeline('text-generation', model='gpt2-medium',batch_size=8,pad_token_id=50256)

def augment_gpt_fake(text):

    current_length = len(text.split())
    target_length = int(np.clip(
      np.random.normal(loc=target_stats['human_fake']['mean'],
                      scale=target_stats['human_fake']['std']),
      target_stats['human_fake']['min'],
      target_stats['human_fake']['max']
  ))
    if current_length >= target_length:
        return text

    # Generate continuation to reach target length
    prompt = text + " "
    additional_tokens = target_length - current_length
    augmented = generator(
        prompt,
        max_new_tokens=additional_tokens+10,
        num_return_sequences=1,
        truncation=True
    )[0]['generated_text']

    return ' '.join(augmented.split()[:target_length])


def augment_gpt_real(text):

    current_length = len(text.split())
    target_length = int(np.clip(
      np.random.normal(loc=target_stats['human_real']['mean'],
                      scale=target_stats['human_real']['std']),
      target_stats['human_real']['min'],
      target_stats['human_real']['max']
  ))
    if current_length >= target_length:
        return text

    # Generate continuation to reach target length
    prompt = text + " "
    additional_tokens = target_length - current_length
    augmented = generator(
        prompt,
        max_new_tokens=additional_tokens+10,
        num_return_sequences=1,
        truncation=True
    )[0]['generated_text']

    return ' '.join(augmented.split()[:target_length])

augmented_samples = []

for idx, row in new_FNN_df[new_FNN_df['label'] == 'gpt_fake'].iterrows():
    augmented = augment_gpt_fake(row['text'])
    augmented_samples.append({
        'text': augmented,
        'label': row['label'],
        'original_length': len(row['text'].split()),
        'new_length': len(augmented.split())
    })

# Convert to DataFrame and merge with original
balanced_df = pd.DataFrame(augmented_samples)


# Verify new length distribution
print(balanced_df.groupby('label')['text'].apply(
    lambda x: x.str.split().str.len().describe()
))

balanced_df = pd.read_csv('/content/drive/MyDrive/DS266/balgptfake.csv')

#concat gpt fake with cleaned human real and human fake

HR =  new_FNN_df[(new_FNN_df['label'] == "human_real")][["combined_text","label"]]
HF =  new_FNN_df[(new_FNN_df['label'] == "human_fake") ][["combined_text","label"]]
MF =  balanced_df[["text","label"]].rename(columns={'text': 'combined_text'})
newBal_FNN_df = pd.concat([MF,HR,HF])

print(newBal_FNN_df['label'].value_counts())

MF = resample(MF,replace=True,n_samples=3777,random_state=42)
HR = resample(HR,replace=True,n_samples=3777,random_state=42)


newBal_FNN_df = pd.concat([MF,HR,HF])

print(newBal_FNN_df['label'].value_counts())

# calcalate word count distributon of news text
newBal_FNN_df["word_count"] = newBal_FNN_df["combined_text"].apply(lambda x: len(x.split()))
newBal_FNN_df.groupby("label")["word_count"].describe()

newBal_FNN_df['cleaned_combined_text'] = newBal_FNN_df['combined_text'].apply(clean_text)

newBal_FNN_df['label_new'] = newBal_FNN_df['label'].map({'human_fake': 0, 'human_real': 1.0,'gpt_fake': 2,'gpt_real':3})

from sklearn.model_selection import train_test_split

# Split the data while keeping the DataFrame structure ( for hugging face dataset use)

train_df, tmp_df = train_test_split(
    newBal_FNN_df[['cleaned_combined_text', 'label_new']],
    test_size=0.4,
    random_state=42,
    stratify=newBal_FNN_df['label_new']
)

val_df, test_df = train_test_split(
    tmp_df,
    test_size=0.5,
    random_state=42,
    stratify=tmp_df['label_new']
)
# Reset the index for both DataFrames
train_df = train_df.reset_index(drop=True)
test_df = test_df.reset_index(drop=True)
val_df = val_df.reset_index(drop=True)

print(f"Training samples: {len(train_df)}")
print(f"Test samples: {len(test_df)}")
print(f"Val samples: {len(test_df)}")
print("\nTrain DataFrame:")
print(train_df.head())
print("\nTest DataFrame:")
print(test_df.head())
print("\nVal DataFrame:")
print(val_df.head())

train_df['text_add_typos'] = train_df.apply(conditional_add_typos, axis=1)
train_df.drop(columns=['cleaned_combined_text'], inplace=True)
train_df

# Convert to Hugging Face Dataset for training
formatted_df1 = train_df.rename(columns={
    'text_add_typos': 'text',
    'label_new': 'label'
})

fake_news_dataset_train = Dataset.from_pandas(formatted_df1)

# Convert to Hugging Face Dataset for testimg
formatted_df2 = test_df.rename(columns={
    'cleaned_combined_text': 'text',
    'label_new': 'label'
})

fake_news_dataset_test = Dataset.from_pandas(formatted_df2)

# Convert to Hugging Face Dataset for validating
formatted_df3 = val_df.rename(columns={
    'cleaned_combined_text': 'text',
    'label_new': 'label'
})

fake_news_dataset_val = Dataset.from_pandas(formatted_df3)

print("Test: \n",fake_news_dataset_test)
print("Train: \n",fake_news_dataset_train)
print("Val: \n",fake_news_dataset_val)

#Creating  compute metrics function

metric = evaluate.load('accuracy')

# FakeNewsNet_df['label_new'] = FakeNewsNet_df['label'].map({'human_fake': 0, 'human_real': 1.0,'gpt_fake': 2,'gpt_real': 3})
def compute_metrics(eval_pred):
  predictions, labels = eval_pred
  predictions = np.argmax(predictions, axis=1)
  precision, recall, f1, _ = precision_recall_fscore_support(labels, predictions, average='weighted')
  acc = accuracy_score(labels, predictions)

  class_report = classification_report(
        labels, predictions,
        target_names=['human_fake', 'human_real', 'gpt_fake'],
        digits=4
    )
  print("\nClassification Report:")
  print(class_report)

  return {
      'accuracy': acc,
      'f1': f1,
      'precision': precision,
      'recall': recall
  }

"""####bert"""

MAX_SEQUENCE_LENGTH = 500

model_checkpoint_name = "bert-base-cased"
bert_tokenizer = AutoTokenizer.from_pretrained(model_checkpoint_name)
# bert_classification_model = AutoModelForSequenceClassification.from_pretrained(model_checkpoint_name)

bert_classification_model = AutoModelForSequenceClassification.from_pretrained(
    model_checkpoint_name,
    num_labels=3  # number of classes = 4
)

fine_tune_classification_model(bert_classification_model, bert_tokenizer, fake_news_dataset_train, fake_news_dataset_val)

"""#### reberta"""

model_checkpoint_name = "roberta-base"
roberta_tokenizer = AutoTokenizer.from_pretrained(model_checkpoint_name)
roberta_classification_model = AutoModelForSequenceClassification.from_pretrained(
    model_checkpoint_name,
    num_labels=3  # number of classes = 4
)

fine_tune_classification_model(roberta_classification_model, roberta_tokenizer, fake_news_dataset_train, fake_news_dataset_val)

"""##CODE SANDBOX"""

# # Bal_FNN_df = pd.concat([balanced_df_real,balanced_df_real])

# balanced_df.to_csv('/content/drive/MyDrive/DS266/balgptfake.csv', index=False)



# augmented_samples = []

# for idx, row in new_FNN_df[new_FNN_df['label'] == 'gpt_real'].iterrows():
#     augmented = augment_gpt_real(row['text'])
#     augmented_samples.append({
#         'text': augmented,
#         'label': row['label'],
#         'original_length': len(row['text'].split()),
#         'new_length': len(augmented.split())
#     })

# # Convert to DataFrame and merge with original
# balanced_df_real = pd.DataFrame(augmented_samples)


# # Verify new length distribution
# print(balanced_df_real.groupby('label')['text'].apply(
#     lambda x: x.str.split().str.len().describe()
# ))

# balanced_df_real.to_csv('/content/drive/MyDrive/DS266/balanced_df_gptreal.csv', index=False)

# Bal_FNN_df = pd.concat([balanced_df_real,balanced_df_real])

# Bal_FNN_df.to_csv('/content/drive/MyDrive/DS266/balanced_data.csv', index=False)

# from google.colab import drive
# drive.mount('/content/drive')  # First mount your Drive

# # Save as CSV
# balanced_df.to_csv('/content/drive/MyDrive/your_folder/balanced_data.csv', index=False)

# Bal_FNN_df.to_parquet('/content/drive/MyDrive/DS266/balanced_data_parq.parquet')