# -*- coding: utf-8 -*-
"""Jianyi(Nancy)Teng_final_project_fake_news_detect(base_and_eval).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_tE-rQbdaa-42yrAO_rkajT20VtmAZw8

##a. LIBRARY INSTALL AND IMPORT
"""

!pip install pandas numpy scikit-learn torch transformers tqdm

# This cell will authenticate you and mount your Drive in the Colab.
from google.colab import drive
drive.mount('/content/drive')

#Import all necessary libraries
import re
import nltk
import os
import json
import pandas as pd
import torch
import numpy as np
from sklearn.utils import resample
from transformers import BertTokenizer, BertModel
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

# check some numpy version
print(f"NumPy version: {np.__version__}")

"""#b.DATA

###b1.DATA LOADING
"""

import json
import pandas as pd

# Function to read a JSON file
def load_json_file(file_path):
    """Load a JSON file"""
    with open(file_path, "r", encoding="utf-8") as file:
        return json.load(file)

# Function to process FakeNewsNet data
def process_FakeNewsNet_data(file_paths):
    """Read multiple JSON files and organize them into a DataFrame"""
    data_list = []  # Store all data

    for category, file_path in file_paths.items():
        data = load_json_file(file_path)  # Load JSON data

        for news_id, news_content in data.items():
            if 'text' in news_content:  # Ensure the text field exists
                # Determine the news source
                if "gossipcop" in category:
                    source = "gossipcop"
                elif "politifact" in category:
                    source = "politifact"
                else:
                    source = "unknown"

                # Determine the news type
                if "R" in category:
                    if "HR" in category:
                        label = "human_real" # Human-written real news
                    else:
                        label = "gpt_real"  # AI-generated real news
                elif "F" in category:
                    if "MF" in category:
                        label = "gpt_fake"  # AI-generated fake news
                    else:
                        label = "human_fake"  # Human-written fake news
                else:
                    label = "unknown"

                data_list.append({
                    "id": news_id,
                    "text": news_content["text"],
                    "title": news_content.get("title", ""),  # Some data may not have a title
                    "source": source,  # News source
                    "label": label,  # Real/fake news category
                })

    # Convert to a Pandas DataFrame
    df = pd.DataFrame(data_list)
    return df

# Define paths for the dataset
fake_news_paths = {
    "gossipcop_HF": "/content/drive/MyDrive/DS266/HF.json",
    "gossipcop_HR": "/content/drive/MyDrive/DS266/HR.json",
    "gossipcop_MF": "/content/drive/MyDrive/DS266/MF.json",
    "gossipcop_MR": "/content/drive/MyDrive/DS266/MR.json",
}

# Load and process the data
FakeNewsNet_df = process_FakeNewsNet_data(fake_news_paths)

# Display the first 5 rows
FakeNewsNet_df.head()

"""##b2.DATA CLEANING"""

# check each label category, there exisT in-balance data
print(FakeNewsNet_df['label'].value_counts())

target_count = FakeNewsNet_df['label'].value_counts().min()
print(target_count)

#Balance the data

MR =  FakeNewsNet_df[FakeNewsNet_df['label'] == "gpt_real"]
MF =  FakeNewsNet_df[FakeNewsNet_df['label'] == "gpt_fake"]
HR =  FakeNewsNet_df[FakeNewsNet_df['label'] == "human_real"]
HF =  FakeNewsNet_df[FakeNewsNet_df['label'] == "human_fake"]

MR = resample(MR,replace=True,n_samples=target_count,random_state=42)
HR = resample(HR,replace=True,n_samples=target_count,random_state=42)


Bal_FNN_df = pd.concat([MR,MF,HR,HF])

print(Bal_FNN_df['label'].value_counts())

# combine text and title for training
Bal_FNN_df['combined_text'] = Bal_FNN_df['text'] + ' ' + Bal_FNN_df['title']

# Convert labels to numerical values (0=real, 1=fake)
Bal_FNN_df['label_new'] = Bal_FNN_df['label'].map({'human_fake': 0, 'human_real': 1.0,'gpt_fake': 2,'gpt_real':3})

# Show sample data
print("Sample data:")
print(Bal_FNN_df[['text','combined_text', 'label','label_new']].head())

# calcalate word count distributon of news text
Bal_FNN_df["word_count"] = Bal_FNN_df["text"].apply(lambda x: len(x.split()))
Bal_FNN_df.groupby("label")["word_count"].describe()

def simple_tokenizer(text):
    return re.findall(r'\b\w+\b', text.lower())

text = "Hello! This is a test."
print(simple_tokenizer(text))

import nltk
nltk.download('stopwords')

import string

# Remove unwanted characters, links, and HTML tags
def clean_text(text):
    # Remove HTML tags
    text = re.sub(r'<.*?>', '', text)
    # Remove URLs
    text = re.sub(r'http\S+|www\S+|https\S+', '', text)
    # Remove special characters and numbers, keeping only letters
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()
    # Convert to lowercase
    text = text.lower()
    words = simple_tokenizer(text)
    stop_words = set(stopwords.words('english'))
    filtered_words = [word for word in words if word not in stop_words]
    return ' '.join(filtered_words)

# Apply cleaning to datasets
Bal_FNN_df['cleaned_combined_text'] = Bal_FNN_df['combined_text'].apply(clean_text)
# Print some cleaned samples

print(Bal_FNN_df['cleaned_combined_text'].head())

"""##b3.TRAIN, TEST AND VALIDATION SPLIT"""

from sklearn.model_selection import train_test_split

X_train, X_temp, y_train, y_temp = train_test_split(
    Bal_FNN_df['combined_text'],
    Bal_FNN_df['label_new'],
    test_size=0.4,
    random_state=42,
    stratify=Bal_FNN_df['label_new']
)


X_test, X_val, y_test, y_val = train_test_split(
    X_temp,
    y_temp,
    test_size=0.5,
    random_state=42,
    stratify=y_temp
)


print(f"Training samples: {len(X_train)}")
print(f"Test samples: {len(X_test)}")
print(f"Valid samples: {len(X_val)}")

"""## c.Baseline Model -  Text Classification.
####  pre-train model used:
#####   1. "roberta-base"
#####   2. "bert-base"
#####   3. "roberta-base-fakenews"
#####   4. "microsoft/deberta-v3-base"

"""

#@title install
!pip install -q transformers
!pip install -q torchinfo
!pip install -q datasets
!pip install -q evaluate

#@title Imports

import numpy as np

import transformers
import evaluate

from datasets import load_dataset
from torchinfo import summary

from transformers import AutoTokenizer, AutoModel, AutoModelForSequenceClassification
from transformers import TrainingArguments, Trainer

import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

import nltk
nltk.download('stopwords')
nltk.download('punkt')

from datasets import Dataset
import pandas as pd

from sklearn.metrics import confusion_matrix, classification_report
import numpy as np


from transformers import Trainer, TrainingArguments
import torch
import numpy as np
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

from sklearn.model_selection import train_test_split

# Split the data while keeping the DataFrame structure ( for hugging face dataset use)

train_df, tmp_df = train_test_split(
    Bal_FNN_df[['cleaned_combined_text', 'label_new']],
    test_size=0.4,
    random_state=42,
    stratify=Bal_FNN_df['label_new']
)

val_df, test_df = train_test_split(
    tmp_df,
    test_size=0.5,
    random_state=42,
    stratify=tmp_df['label_new']
)
# Reset the index for both DataFrames
train_df = train_df.reset_index(drop=True)
test_df = test_df.reset_index(drop=True)
val_df = val_df.reset_index(drop=True)

print(f"Training samples: {len(train_df)}")
print(f"Test samples: {len(test_df)}")
print(f"Val samples: {len(test_df)}")
print("\nTrain DataFrame:")
print(train_df.head())
print("\nTest DataFrame:")
print(test_df.head())
print("\nVal DataFrame:")
print(val_df.head())

# Convert to Hugging Face Dataset for training
formatted_df = train_df.rename(columns={
    'cleaned_combined_text': 'text',
    'label_new': 'label'
})

fake_news_dataset_train = Dataset.from_pandas(formatted_df)

# Convert to Hugging Face Dataset for testimg
formatted_df = test_df.rename(columns={
    'cleaned_combined_text': 'text',
    'label_new': 'label'
})

fake_news_dataset_test = Dataset.from_pandas(formatted_df)

# Convert to Hugging Face Dataset for validating
formatted_df = val_df.rename(columns={
    'cleaned_combined_text': 'text',
    'label_new': 'label'
})

fake_news_dataset_val = Dataset.from_pandas(formatted_df)

print("Test: \n",fake_news_dataset_test)
print("Train: \n",fake_news_dataset_train)
print("Val: \n",fake_news_dataset_val)

MAX_SEQUENCE_LENGTH = 500
# to get 75% for all 4 class, choose max_sequence small than longest class.


# |label|count|mean|std|min|25%|50%|75%|max|
# |---|---|---|---|---|---|---|---|---|
# |gpt\_fake|4084\.0|225\.1488736532811|51\.69881948866794|8\.0|192\.0|222\.0|255\.0|520\.0|
# |gpt\_real|4084\.0|368\.9422135161606|252\.5846971492773|1\.0|262\.0|331\.0|413\.0|4292\.0|
# |human\_fake|4084\.0|467\.4111165523996|714\.3845834167945|5\.0|182\.0|339\.0|483\.0|16373\.0|
# |human\_real|4084\.0|529\.7477962781587|795\.6128398262819|4\.0|218\.0|355\.0|578\.0|17224\.0|

# Encode data

def preprocess_data(data, tokenizer):
    review_text = data['text']

    encoded = tokenizer.batch_encode_plus(
            review_text,
            max_length=MAX_SEQUENCE_LENGTH,
            padding='max_length',
            truncation=True,
            return_attention_mask=True,
            return_token_type_ids=True,
            return_tensors="pt"
        )

    return encoded

#Creating  compute metrics function

metric = evaluate.load('accuracy')

# FakeNewsNet_df['label_new'] = FakeNewsNet_df['label'].map({'human_fake': 0, 'human_real': 1.0,'gpt_fake': 2,'gpt_real': 3})
def compute_metrics(eval_pred):
  predictions, labels = eval_pred
  predictions = np.argmax(predictions, axis=1)
  precision, recall, f1, _ = precision_recall_fscore_support(labels, predictions, average='weighted')
  acc = accuracy_score(labels, predictions)

  class_report = classification_report(
        labels, predictions,
        target_names=['human_fake', 'human_real', 'gpt_fake','gpt_real'],
        digits=4
    )
  print("\nClassification Report:")
  print(class_report)

  return {
      'accuracy': acc,
      'f1': f1,
      'precision': precision,
      'recall': recall
  }

## Fine tuning the "bert-base-cased" model

def fine_tune_classification_model(classification_model,
                                   tokenizer,
                                   train_data,
                                   val_data,
                                   batch_size = 16,
                                   num_epochs = 3):

    preprocessed_train_data = train_data.map(preprocess_data, batched=True, fn_kwargs={'tokenizer': tokenizer})
    preprocessed_val_data = val_data.map(preprocess_data, batched=True, fn_kwargs={'tokenizer': tokenizer})

    preprocessed_train_data = preprocessed_train_data.map(
        lambda x: {'labels': torch.tensor(x['label'], dtype=torch.long)}  # Ensure labels are int64
    )
    preprocessed_val_data  = preprocessed_val_data .map(
        lambda x: {'labels': torch.tensor(x['label'], dtype=torch.long)}
    )



    training_args = TrainingArguments(
    output_dir="/content/drive/MyDrive/DS266/model_output",
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size,
    num_train_epochs=num_epochs,
    logging_dir="/content/drive/MyDrive/DS266/logs",
    eval_strategy="epoch",
    save_strategy="epoch",
    report_to='none'
)
    trainer = Trainer(
        model=classification_model,
        args=training_args,
        train_dataset=preprocessed_train_data,
        eval_dataset=preprocessed_val_data,
        compute_metrics=compute_metrics
    )


    trainer.train()



"""### c1: bert-base model"""

model_checkpoint_name = "bert-base-cased"
bert_tokenizer = AutoTokenizer.from_pretrained(model_checkpoint_name)
# bert_classification_model = AutoModelForSequenceClassification.from_pretrained(model_checkpoint_name)

bert_classification_model = AutoModelForSequenceClassification.from_pretrained(
    model_checkpoint_name,
    num_labels=4  # number of classes = 4
)

fine_tune_classification_model(bert_classification_model, bert_tokenizer, fake_news_dataset_train, fake_news_dataset_val)

"""### c2: roberta-base model"""

model_checkpoint_name = "roberta-base"
roberta_tokenizer = AutoTokenizer.from_pretrained(model_checkpoint_name)
roberta_classification_model = AutoModelForSequenceClassification.from_pretrained(
    model_checkpoint_name,
    num_labels=4  # number of classes = 4
)

fine_tune_classification_model(roberta_classification_model, roberta_tokenizer, fake_news_dataset_train, fake_news_dataset_val)

# too time consuming,

# model_checkpoint_name = "roberta-large"
# roberta2_tokenizer = AutoTokenizer.from_pretrained(model_checkpoint_name)
# roberta2_classification_model = AutoModelForSequenceClassification.from_pretrained(
#     model_checkpoint_name,
#     num_labels=4  # number of classes = 4
# )

# fine_tune_classification_model(roberta2_classification_model, roberta2_tokenizer, fake_news_dataset_train, fake_news_dataset_val)

"""### c3: distilbert model"""

model_checkpoint_name = "distilbert-base-uncased"
distilbert_tokenizer = AutoTokenizer.from_pretrained(model_checkpoint_name)
distilbert_classification_model = AutoModelForSequenceClassification.from_pretrained(
    model_checkpoint_name,
    num_labels=4  # number of classes = 4
)

fine_tune_classification_model(distilbert_classification_model, distilbert_tokenizer, fake_news_dataset_train, fake_news_dataset_val)

from transformers import BertTokenizer, BertForSequenceClassification

# save bert model for later evaluation
base_classifier_checkpoint_filepath = '/content/drive/MyDrive/DS266/model_checkpoint/base_classifier'
bert_classification_model.save_pretrained(base_classifier_checkpoint_filepath, from_pt=True)

# bert_classification_model = BertForSequenceClassification.from_pretrained(base_classifier_checkpoint_filepath)

# save roberta model for later evaluation
base_classifier_checkpoint_filepath_roberta = '/content/drive/MyDrive/DS266/model_checkpoint/base_classifier_roberta'
roberta_classification_model.save_pretrained(base_classifier_checkpoint_filepath_roberta, from_pt=True)

# roberta_classification_model = robertaForSequenceClassification.from_pretrained(base_classifier_checkpoint_filepath_roberta)

# save distilbert model for later evaluation
base_classifier_checkpoint_filepath_distilbert= '/content/drive/MyDrive/DS266/model_checkpoint/base_classifier_distilbert'
distilbert_classification_model.save_pretrained(base_classifier_checkpoint_filepath_distilbert, from_pt=True)

# roberta_classification_model = robertaForSequenceClassification.from_pretrained(base_classifier_checkpoint_filepath_roberta)

"""##d. Base Line Model Evaluation

Current base line model proceed with bert, distilbert, and roberta finetunning having bias on GPT generated text. There exist overfitting on both MF and MR label.

Question for this section: Why overfitting?

### d1.Feature-Level Diagnostics -  feature contribution

Useful Resource: https://pmc.ncbi.nlm.nih.gov/articles/PMC11513550/
"""

# Load Model saved
# save_path2 = '/content/drive/MyDrive/DS266/model_checkpoint/base_classifier_wthclean'
save_path_b = '/content/drive/MyDrive/DS266/model_checkpoint/base_classifier'
save_path_r = '/content/drive/MyDrive/DS266/model_checkpoint/base_classifier_roberta'
save_path_d = '/content/drive/MyDrive/DS266/model_checkpoint/base_classifier_distilbert'

from transformers import AutoTokenizer, AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(save_path_b)
model_name = "bert-base-cased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

import shap
from transformers import pipeline
# Load trained model
classifier = pipeline(
    task="text-classification",
    model=model,
    tokenizer=tokenizer,
    device=0
)
explainer = shap.Explainer(classifier)

"""###### d.1.0: test with sample data"""

#test with one gpt fake result.
# LABEL: ({'human_fake': 0, 'human_real': 1.0,'gpt_fake': 2,'gpt_real': 3})

test_text = "Excitement and anticipation are in the air as the Royal Family gets ready to welcome their newest member. Prince Harry has finally proposed to his girlfriend Meghan Markle and the couple is set to tie the knot in the spring of 2018. \n\nSpeculations have been swirling for months that the couple was planning to get engaged, and today the news has finally been confirmed. The public has fallen in love with the American actress and her fashion sense, down-to-earth personality, and charitable works. The Royal Family, too, is reportedly ecstatic about the prospect of having such a \"modern\" bride.\n\nMany pundits have praised Prince Harry for choosing someone outside of the typical royal circles, and believe that Meghan Markle brings much-needed diversity to the monarchy. Markle is of mixed race, divorced, and a successful actress in her own right. Her engagement to Prince Harry is already being hailed as a critical moment in royal history.\n\nRumor has it that the wedding preparations are already underway, and that the couple is determined to make their big day a memorable one. There are already some reports that they plan to buck tradition when it comes to everything from the guest list to the style of dress. However, the Royal Family has been tight-lipped about any details.\n\nOne thing is for certain: the world will be watching as Prince Harry and Meghan Markle exchange their vows in spring 2018. The couple has already won the hearts of millions around the globe, and their wedding is shaping up to be a \"can't miss\" event. Stay tuned for more updates as the big day approaches!."

result = classifier(test_text)
print(f"{result[0]['label']},  {result[0]['score']:.2f}")

print( classifier.tokenizer.tokenize(test_text))

shap_values_test = explainer([test_text])
shap_values_test.values.shape

#(4 is label count)

tokens = classifier.tokenizer.tokenize(test_text)
ai_class_index = classifier.model.config.label2id["LABEL_2"] ## gpt fake is the most overfitting label
shap_scores = shap_values_test[0, :len(tokens), ai_class_index].values

word_contributions = {
    token: score for token, score in zip(tokens, shap_scores)
}

sorted_contributions = sorted(
    word_contributions.items(),
    key=lambda x: -abs(x[1])
)

print("Important word lead to LABEL2 : \n")
for token, score in sorted_contributions[:10]:
    print(f"{token}: contribution score: {score:+.4f} ")

#test with clean, 100 samples
filtered_df = test_df[test_df['label_new'] == 2.0]
## model not seen data

sampled_df = filtered_df.sample(n=100, random_state=42)

text_list = sampled_df['cleaned_combined_text'].tolist()

print(text_list)

#test with clean, 100 samples
filtered_df_r = test_df[
    (test_df['label_new'] == 3.0) &
    (test_df['cleaned_combined_text'].str.split().str.len() <= 400)
]
## model not seen data

sampled_df_r = filtered_df_r.sample(n=100, random_state=42)

text_list_r = sampled_df_r['cleaned_combined_text'].tolist()

print(text_list_r )

"""###### d.1.1: Bert"""

shap_values= explainer(text_list)

import numpy as np
from collections import defaultdict


global_avg = defaultdict(list)
global_max = defaultdict(float)


for sample_idx, text in enumerate(text_list):
    tokens = classifier.tokenizer.tokenize(text)

    ai_class_index = classifier.model.config.label2id["LABEL_2"]
    shap_scores = shap_values[sample_idx, :len(tokens), ai_class_index].values

    for token, score in zip(tokens, shap_scores):
        global_avg[token].append(score)
        if score > global_max[token]:
            global_max[token] = score

def print_top_stats(stats_dict, title, value_format="+.4f"):
    filtered_items = [
        (token, score)
        for token, score in stats_dict.items()
    ]
    sorted_items = sorted(filtered_items, key=lambda x: -x[1])

    print(f"\n{title}:")
    for token, value in sorted_items[:10]:
        print(f"  {token} : {value:{value_format}}")

avg_score = {token: np.mean(scores) for token, scores in global_avg.items()}
print_top_stats(avg_score, "Average Score")

print_top_stats(global_max, "Max Score")

shap.plots.text(shap_values[50, :, ai_class_index])





text_list_r_filtered = [
    text for text in text_list_r
    if len(tokenizer.tokenize(text)) <= 512
]

shap_values= explainer(text_list_r_filtered)


global_avg = defaultdict(list)
global_max = defaultdict(float)


for sample_idx, text in enumerate(text_list_r_filtered):
    tokens = classifier.tokenizer.tokenize(text)

    ai_class_index = classifier.model.config.label2id["LABEL_2"]
    shap_scores = shap_values[sample_idx, :len(tokens), ai_class_index].values

    for token, score in zip(tokens, shap_scores):
        global_avg[token].append(score)
        if score > global_max[token]:
            global_max[token] = score

def print_top_stats(stats_dict, title, value_format="+.4f"):
    filtered_items = [
        (token, score)
        for token, score in stats_dict.items()
    ]
    sorted_items = sorted(filtered_items, key=lambda x: -x[1])

    print(f"\n{title}:")
    for token, value in sorted_items[:10]:
        print(f"  {token} : {value:{value_format}}")

avg_score = {token: np.mean(scores) for token, scores in global_avg.items()}
print_top_stats(avg_score, "Average Score")

print_top_stats(global_max, "Max Score")

"""###### d.1.2: Roberta"""

model = AutoModelForSequenceClassification.from_pretrained(save_path_r)
model_name = "roberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Load trained model
classifier = pipeline(
    task="text-classification",
    model=model,
    tokenizer=tokenizer,
    device=0
)


shap_values = explainer(text_list)

import numpy as np
from collections import defaultdict


global_avg = defaultdict(list)
global_max = defaultdict(float)


for sample_idx, text in enumerate(text_list):
    tokens = classifier.tokenizer.tokenize(text)

    ai_class_index = classifier.model.config.label2id["LABEL_2"]
    shap_scores = shap_values[sample_idx, :len(tokens), ai_class_index].values

    for token, score in zip(tokens, shap_scores):
        global_avg[token].append(score)
        if score > global_max[token]:
            global_max[token] = score

def print_top_stats(stats_dict, title, value_format="+.4f"):
    filtered_items = [
        (token, score)
        for token, score in stats_dict.items()
    ]
    sorted_items = sorted(filtered_items, key=lambda x: -x[1])

    print(f"\n{title}:")
    for token, value in sorted_items[:10]:
        print(f"  {token} : {value:{value_format}}")

avg_score = {token: np.mean(scores) for token, scores in global_avg.items()}
print_top_stats(avg_score, "Average Score")

print_top_stats(global_max, "Max Score")

"""###### d.1.3: Distilbert"""

model = AutoModelForSequenceClassification.from_pretrained(save_path_d)
model_name = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Load trained model
classifier = pipeline(
    task="text-classification",
    model=model,
    tokenizer=tokenizer,
    device=0
)


shap_values = explainer(text_list)

import numpy as np
from collections import defaultdict


global_avg = defaultdict(list)
global_max = defaultdict(float)


for sample_idx, text in enumerate(text_list):
    tokens = classifier.tokenizer.tokenize(text)

    ai_class_index = classifier.model.config.label2id["LABEL_2"]
    shap_scores = shap_values[sample_idx, :len(tokens), ai_class_index].values

    for token, score in zip(tokens, shap_scores):
        global_avg[token].append(score)
        if score > global_max[token]:
            global_max[token] = score

def print_top_stats(stats_dict, title, value_format="+.4f"):
    filtered_items = [
        (token, score)
        for token, score in stats_dict.items()
    ]
    sorted_items = sorted(filtered_items, key=lambda x: -x[1])

    print(f"\n{title}:")
    for token, value in sorted_items[:10]:
        print(f"  {token} : {value:{value_format}}")

avg_score = {token: np.mean(scores) for token, scores in global_avg.items()}
print_top_stats(avg_score, "Average Score")

print_top_stats(global_max, "Max Score")





"""### d2.Feature-Level Diagnostics -  n_grams frequency

"""

df = Bal_FNN_df[["cleaned_combined_text","label"]]

ai_texts = df[df["label"] == "gpt_fake"]["cleaned_combined_text"].tolist()

len(ai_texts)

from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd


# Extract n-grams from AI-generated texts
vectorizer = CountVectorizer(ngram_range=(2,3), max_features=100)
X = vectorizer.fit_transform(ai_texts)

# Get top 20 trigrams
ngram_freq = pd.DataFrame(X.sum(axis=0), columns=vectorizer.get_feature_names_out())
top_ngrams = ngram_freq.T.sort_values(0, ascending=False).head(20)
print(top_ngrams)

"""### d3.Model-Level Diagnostics - robustness analysis"""

# https://arxiv.org/pdf/1901.08644  cite paper.

# https://github.com/marcotcr/checklist github

# https://homes.cs.washington.edu/~marcotcr/acl20_checklist.pdf cite paper.

pip cache purge

!pip install checklist

import checklist
from checklist.editor import Editor
from checklist.perturb import Perturb
import spacy
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import pandas as pd
from transformers import pipeline

editor = Editor()

nlp = spacy.load('en_core_web_sm')



test_df['spacy_docs'] = test_df['cleaned_combined_text'].apply(nlp)
test_df['text_perturbed'] = test_df['spacy_docs'].apply(
    lambda doc: Perturb.strip_punctuation(doc)
)

test_df['text_add_typos'] = test_df['cleaned_combined_text'].apply(
    lambda doc: Perturb.add_typos(doc)
)

from datasets import Dataset
import pandas as pd

formatted_df = test_df[['text_add_typos','label_new']].rename(columns={
    'text_add_typos': 'text',
    'label_new': 'label'
})

# 2. Convert to Hugging Face Dataset
fake_news_dataset_test_withtypo = Dataset.from_pandas(formatted_df)

from datasets import Dataset
import pandas as pd

formatted_df = test_df[['text_perturbed','label_new']].rename(columns={
    'text_perturbed': 'text',
    'label_new': 'label'
})

# 2. Convert to Hugging Face Dataset
fake_news_dataset_test_wiopun = Dataset.from_pandas(formatted_df)

def eval_model(model, tokenizer,MAX_SEQUENCE_LENGTH,ds):
  preprocessed_val_data = ds.map(preprocess_data, batched=True, fn_kwargs={'tokenizer': tokenizer})
  preprocessed_val_data  = preprocessed_val_data .map(
          lambda x: {'labels': torch.tensor(x['label'], dtype=torch.long)}
      )

  trainer = Trainer(
      model=model,
      eval_dataset=preprocessed_val_data,
      compute_metrics=compute_metrics,)

  results = trainer.evaluate()

  print(f"\nEvaluation Results:")
  for k, v in results.items():
      print(f"{k}: {v:.4f}")

"""#####d.3.1 BERT"""

MAX_SEQUENCE_LENGTH = 500
model = AutoModelForSequenceClassification.from_pretrained(save_path_b)
model_name = "bert-base-cased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

print("After Applying typo:\n")
eval_model(model, tokenizer,MAX_SEQUENCE_LENGTH,fake_news_dataset_test_withtypo)
print("\n")
print("After Applying remove pun:\n")
eval_model(model, tokenizer,MAX_SEQUENCE_LENGTH,fake_news_dataset_test_wiopun)
print("\n")

"""#####d.3.2 roberta-base"""

MAX_SEQUENCE_LENGTH = 500
model = AutoModelForSequenceClassification.from_pretrained(save_path_r)
model_name = "roberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)

print("After Applying typo:\n")
eval_model(model, tokenizer,MAX_SEQUENCE_LENGTH,fake_news_dataset_test_withtypo)
print("\n")
print("After Applying remove pun:\n")
eval_model(model, tokenizer,MAX_SEQUENCE_LENGTH,fake_news_dataset_test_wiopun)
print("\n")

"""#####d.3.3 distilbert-base-uncased"""

MAX_SEQUENCE_LENGTH = 500
model = AutoModelForSequenceClassification.from_pretrained(save_path_d)
model_name = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

print("After Applying typo:\n")
eval_model(model, tokenizer,MAX_SEQUENCE_LENGTH,fake_news_dataset_test_withtypo)
print("\n")
print("After Applying remove pun:\n")
eval_model(model, tokenizer,MAX_SEQUENCE_LENGTH,fake_news_dataset_test_wiopun)
print("\n")





















"""##CODE SANDBOX

"""

# import json
# import pandas as pd

# # Function to read a JSON file
# def load_json_file(file_path):
#     """Load a JSON file"""
#     with open(file_path, "r", encoding="utf-8") as file:
#         return json.load(file)

# # Function to process FakeNewsNet data
# def process_FakeNewsNet_data(file_paths):
#     """Read multiple JSON files and organize them into a DataFrame"""
#     data_list = []  # Store all data

#     for category, file_path in file_paths.items():
#         data = load_json_file(file_path)  # Load JSON data

#         for news_id, news_content in data.items():
#             if 'text' in news_content:  # Ensure the text field exists
#                 # Determine the news source
#                 if "gossipcop" in category:
#                     source = "gossipcop"
#                 elif "politifact" in category:
#                     source = "politifact"
#                 else:
#                     source = "unknown"

#                 # Determine the news type
#                 if "HR" in category:
#                     label = "human_real"  # Human-written real news
#                 elif "F" in category:
#                     if "MF" in category:
#                         label = "gpt_fake"  # AI-generated fake news
#                     else:
#                         label = "human_fake"  # Human-written fake news
#                 else:
#                     label = "unknown"

#                 data_list.append({
#                     "id": news_id,
#                     "text": news_content["text"],
#                     "title": news_content.get("title", ""),  # Some data may not have a title
#                     "source": source,  # News source
#                     "label": label,  # Real/fake news category
#                 })

#     # Convert to a Pandas DataFrame
#     df = pd.DataFrame(data_list)
#     return df

# # Define paths for the dataset
# fake_news_paths = {
#     "gossipcop_HF": "/content/drive/MyDrive/DS266/HF.json",
#     "gossipcop_HR": "/content/drive/MyDrive/DS266/HR.json",
#     "gossipcop_MF": "/content/drive/MyDrive/DS266/MF.json",
# }

# # Load and process the data
# FakeNewsNet_df = process_FakeNewsNet_data(fake_news_paths)

# # Display the first 5 rows
# FakeNewsNet_df.head()

# import random
# import pandas as pd
# from typing import Dict, List

# class GPTTextHumanizer:
#     def __init__(self, error_prob: float = 0.18):
#         self.error_prob = error_prob
#         self.error_config = {
#             # Tiered error probabilities (more likely errors first)
#             'common_typos': {
#                 'prob': 0.6,
#                 'map': {
#                     'the': ['teh', 'th'],
#                     'and': ['adn', 'an'],
#                     'that': ['taht'],
#                     'with': ['wit'],
#                     'this': ['tis']
#                 }
#             },
#             'case_errors': {
#                 'prob': 0.4,
#                 'apply': lambda word: ''.join(
#                     c.upper() if random.random() < 0.3 else c.lower()
#                     for c in word
#                 )
#             },
#             'filler_words': {
#                 'prob': 0.3,
#                 'words': ['like', 'you know', 'I mean', 'sorta', 'kinda']
#             },
#         }

#     def _apply_typos(self, word: str) -> str:
#         if random.random() < self.error_config['common_typos']['prob']:
#             lower_word = word.lower()
#             if lower_word in self.error_config['common_typos']['map']:
#                 return random.choice(
#                     self.error_config['common_typos']['map'][lower_word]
#                 )
#         return word

#     def _apply_case_errors(self, word: str) -> str:
#         if random.random() < self.error_config['case_errors']['prob']:
#             return self.error_config['case_errors']['apply'](word)
#         return word

#     def _insert_fillers(self, text: str) -> str:
#         if random.random() < self.error_config['filler_words']['prob']:
#             words = text.split()
#             if len(words) > 4:
#                 insert_pos = random.randint(1, len(words)-1)
#                 filler = random.choice(
#                     self.error_config['filler_words']['words']
#                 )
#                 words.insert(insert_pos, filler)
#                 return ' '.join(words)
#         return text


#     def humanize(self, text: str) -> str:
#         if not isinstance(text, str):
#             return text

#         # Apply transformations in order of most to least disruptive
#         words = text.split()
#         words = [self._apply_case_errors(self._apply_typos(word))
#                 for word in words]
#         text = ' '.join(words)
#         text = self._insert_fillers(text)

#         return text

# def replace_gpt_fake_text(
#     df: pd.DataFrame,
#     target_label: str = "gpt_fake",
#     text_col: str = "text"
# ) -> pd.DataFrame:

#     humanizer = GPTTextHumanizer()

#     # Create mask for target rows
#     target_mask = df['label'] == target_label

#     # Apply humanization
#     df.loc[target_mask, text_col] = df.loc[target_mask, text_col].apply(
#         lambda x: humanizer.humanize(x)
#     )

#     return df

# # Example usage:
# # df = pd.read_csv('your_data.csv')
# # print("Before:", df[df['label'] == "gpt_fake"]['text'].iloc[0])
# # replace_gpt_fake_text(df, target_label="gpt_fake")
# # print("After:", df[df['label'] == "gpt_fake"]['text'].iloc[0])
# # df.to_csv('humanized_output.csv', index=False)

# replace_gpt_fake_text(FakeNewsNet_df, target_label="gpt_fake")

# # FakeNewsNet_df_with_human_error = augment_gpt_fake_data(FakeNewsNet_df, target_label="gpt_fake")

# # Load the dataset (update path to your file)
# FakeNewsNet_df['combined_text'] = FakeNewsNet_df['text'] + ' ' + FakeNewsNet_df['title']

# # Convert labels to numerical values (0=real, 1=fake)
# FakeNewsNet_df['label_new'] = FakeNewsNet_df['label'].map({'human_fake': 0, 'human_real': 1.0,'gpt_fake': 2})

# # Show sample data
# print("Sample data:")
# print(FakeNewsNet_df[['text','combined_text', 'label','label_new']].head())

# FakeNewsNet_df

# import string

# # Remove unwanted characters, links, and HTML tags
# def clean_text(text):
#     # Remove HTML tags
#     text = re.sub(r'<.*?>', '', text)
#     # Remove URLs
#     text = re.sub(r'http\S+|www\S+|https\S+', '', text)
#     # Remove special characters and numbers, keeping only letters
#     text = re.sub(r'[^a-zA-Z\s]', '', text)
#     # Remove extra spaces
#     text = re.sub(r'\s+', ' ', text).strip()
#     # Convert to lowercase
#     text = text.lower()
#     return text

# # Apply cleaning to datasets
# FakeNewsNet_df['cleaned_combined_text'] = FakeNewsNet_df['combined_text'].apply(clean_text)
# # Print some cleaned samples

# print(FakeNewsNet_df['cleaned_combined_text'].head())

# from sklearn.model_selection import train_test_split

# # Split the data while keeping the DataFrame structure
# train_df, test_df = train_test_split(
#     FakeNewsNet_df[['cleaned_combined_text', 'label_new']],  # Select both columns
#     test_size=0.3,
#     random_state=42,
#     stratify=FakeNewsNet_df['label_new']
# )

# # Reset the index for both DataFrames
# train_df = train_df.reset_index(drop=True)
# test_df = test_df.reset_index(drop=True)

# print(f"Training samples: {len(train_df)}")
# print(f"Test samples: {len(test_df)}")
# print("\nTrain DataFrame:")
# print(train_df.head())
# print("\nTest DataFrame:")
# print(test_df.head())

# from datasets import Dataset
# import pandas as pd
# formatted_df = train_df.rename(columns={
#     'cleaned_combined_text': 'text',
#     'label_new': 'label'
# })

# # 2. Convert to Hugging Face Dataset
# fake_news_dataset_train = Dataset.from_pandas(formatted_df)

# from datasets import Dataset
# import pandas as pd

# formatted_df = test_df.rename(columns={
#     'cleaned_combined_text': 'text',
#     'label_new': 'label'
# })

# # 2. Convert to Hugging Face Dataset
# fake_news_dataset_test = Dataset.from_pandas(formatted_df)

# fake_news_dataset_test

# fake_news_dataset_train

# def preprocess_imdb(data, tokenizer):
#     review_text = data['text']

#     encoded = tokenizer.batch_encode_plus(
#             review_text,
#             max_length=MAX_SEQUENCE_LENGTH,
#             padding='max_length',
#             truncation=True,
#             return_attention_mask=True,
#             return_token_type_ids=True,
#             return_tensors="pt"
#         )

#     return encoded



# def fine_tune_classification_model(classification_model,
#                                    tokenizer,
#                                    train_data,
#                                    dev_data,
#                                    batch_size = 16,
#                                    num_epochs = 10):

#     preprocessed_train_data = train_data.map(preprocess_imdb, batched=True, fn_kwargs={'tokenizer': tokenizer})
#     preprocessed_dev_data = dev_data.map(preprocess_imdb, batched=True, fn_kwargs={'tokenizer': tokenizer})

#     preprocessed_train_data = preprocessed_train_data.map(
#         lambda x: {'labels': torch.tensor(x['label'], dtype=torch.long)}  # Ensure labels are int64
#     )
#     preprocessed_dev_data  = preprocessed_dev_data .map(
#         lambda x: {'labels': torch.tensor(x['label'], dtype=torch.long)}
#     )


#     ### YOUR CODE HERE


#     training_args = TrainingArguments(
#     output_dir="/content/drive/MyDrive/DS266/model_output",
#     per_device_train_batch_size=batch_size,
#     per_device_eval_batch_size=batch_size,
#     num_train_epochs=num_epochs,
#     logging_dir="/content/drive/MyDrive/DS266/logs",
#     eval_strategy="epoch",
#     save_strategy="epoch",
#     report_to='none'
# )
#     trainer = Trainer(
#         model=classification_model,
#         args=training_args,
#         train_dataset=preprocessed_train_data,
#         eval_dataset=preprocessed_dev_data,
#         compute_metrics=compute_metrics
#     )




#     trainer.train()

# from transformers import Trainer, TrainingArguments
# import torch
# import numpy as np
# from sklearn.metrics import accuracy_score, precision_recall_fscore_support

# model_checkpoint_name = "bert-base-cased"
# bert_tokenizer = AutoTokenizer.from_pretrained(model_checkpoint_name)
# # bert_classification_model = AutoModelForSequenceClassification.from_pretrained(model_checkpoint_name)
# bert_classification_model = AutoModelForSequenceClassification.from_pretrained(
#     model_checkpoint_name,
#     num_labels=3  # number of classes = 3
# )


# MAX_SEQUENCE_LENGTH = 400

# fine_tune_classification_model(bert_classification_model, bert_tokenizer, fake_news_dataset_train, fake_news_dataset_test)

# fine_tune_classification_model(bert_classification_model, bert_tokenizer, fake_news_dataset_train, fake_news_dataset_test)



# from checklist.perturb import Perturb

# def safe_add_typos(text, min_length=3, max_typos=2):
#     """Add typos only to sufficiently long text"""
#     if pd.isna(text) or len(text) < min_length:
#         return text  # Return original if too short

#     try:
#         # Calculate safe number of typos
#         n_typos = min(max_typos, len(text)//2)  # Max 1 typo per 2 characters
#         return Perturb.add_typos(text)
#     except ValueError:
#         return text  # Fallback for edge cases

# def conditional_add_typos(row):
#     """Add typos only to samples with label=2 (AI-generated)"""
#     if row['label_new'] == 2.0 or row['label_new'] == 3.0:
#         return safe_add_typos(row['cleaned_combined_text'])
#     else:
#         return row['cleaned_combined_text']  # Return original for other labels



# train_df['text_add_typos'] = train_df.apply(conditional_add_typos, axis=1)

# test_df['text_add_typos'] = test_df.apply(conditional_add_typos, axis=1)


# # train_df['text_add_typos'] = train_df['cleaned_combined_text'].apply(safe_add_typos)

# # # Verify
# # empty_count = train_df['cleaned_combined_text'].apply(lambda x: len(x) < 3).sum()
# # print(f"Fixed {empty_count} short/empty texts")

# from datasets import Dataset
# import pandas as pd

# formatted_df = test_df[['text_add_typos','label_new']].rename(columns={
#     'text_add_typos': 'text',
#     'label_new': 'label'
# })

# # 2. Convert to Hugging Face Dataset
# fake_news_dataset_test_withtypo = Dataset.from_pandas(formatted_df)

# from datasets import Dataset
# import pandas as pd

# formatted_df = train_df[['text_add_typos','label_new']].rename(columns={
#     'text_add_typos': 'text',
#     'label_new': 'label'
# })

# # 2. Convert to Hugging Face Dataset
# fake_news_dataset_train_withtypo = Dataset.from_pandas(formatted_df)

# fine_tune_classification_model(bert_classification_model, bert_tokenizer, fake_news_dataset_train_withtypo, fake_news_dataset_test_withtypo)

fine_tune_classification_model(bert_classification_model, bert_tokenizer, fake_news_dataset_train_withtypo, fake_news_dataset_test_withtypo)

### import pandas as pd
# import numpy as np
# import re
# import nltk
# from nltk.corpus import stopwords
# from nltk.stem import WordNetLemmatizer
# from sklearn.model_selection import train_test_split
# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.linear_model import LogisticRegression
# from sklearn.metrics import classification_report, accuracy_score
# from sklearn.pipeline import Pipeline
# from sklearn.preprocessing import LabelEncoder
# import xgboost as xgb
# import matplotlib.pyplot as plt

# nltk.download('stopwords')
# nltk.download('wordnet')
# nltk.download('omw-1.4')

# from sklearn.feature_extraction.text import TfidfVectorizer

# # Cell 6: Baseline Model 1 - TF-IDF + Logistic Regression
# # Create pipeline
# lr_pipeline = Pipeline([
#     ('tfidf', TfidfVectorizer(
#         max_features=10000,
#         ngram_range=(1, 2),
#         stop_words='english'
#     )),
#     ('clf', LogisticRegression(
#         max_iter=1000,
#         class_weight='balanced',
#         multi_class='multinomial'
#     ))
# ])

# # Train model
# lr_pipeline.fit(X_train, y_train)

# # Evaluate
# y_pred = lr_pipeline.predict(X_test)

# print("Logistic Regression Results:")
# print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
# print("\nClassification Report:")
# print(classification_report(y_test, y_pred))